### PR TITLE
fix #25 - Show need-infos separately from other bugs in Triage view

### LINKED ISSUE #25: Show need-infos separaretly from other bugs in triage view
This is so we know not to re-triage stuff.

### PR DESCRIPTION
**Pull request by piatra**

### CODE REVIEW

File: src/config/tags.js [hunk 1]
```diff
@@ -5,6 +5,10 @@ module.exports = {
     style: {color: "var(--red-50)", fontWeight: "bold"},
     label: "defect"
   },
+  "NEEDINFO": {
+    style: {color: "var(--gray-90)", fontWeight: "bold"},
+    label: "🤔 needinfo"
```
Comment (k88hudson) [inline src/config/tags.js]: lol i love this

File: src/content/components/Triage/Triage.js [hunk 2]
```diff
@@ -36,12 +36,21 @@ export class Triage extends React.PureComponent {
     });
     this.setState({loaded: true, bugs, prevIterationBugs, prevIteration: prevIteration.number});
   }
+  // Separate out bugs with needinfo, we don't want to triage them until the request is resolved
```
Comment (k88hudson) [inline src/content/components/Triage/Triage.js]: You need to add `flags` to line 27 for the `include_fields` columns in order for flags to be included

**Comment by piatra** [comment]
Updated!
